# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-01 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField()),
                ('deleted_ad', models.DateTimeField(default=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('used', models.IntegerField()),
                ('free', models.IntegerField()),
                ('percent', models.FloatField()),
                ('deleted_ad', models.DateTimeField(default=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('used', models.IntegerField()),
                ('free', models.IntegerField()),
                ('percent', models.FloatField()),
                ('sin', models.IntegerField()),
                ('sout', models.IntegerField()),
                ('deleted_ad', models.DateTimeField(default=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=255)),
                ('server_description', models.TextField()),
                ('deleted_ad', models.DateTimeField(default=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Server_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_id', models.ManyToManyField(to='monitor.Server')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ram',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Server'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Server'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Server'),
        ),
    ]
