# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='deleted_ad',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='deleted_ad',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='deleted_ad',
        ),
        migrations.AlterField(
            model_name='server',
            name='deleted_ad',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
