# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20171201_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='deleted_ad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
