# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-01 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20171201_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='deleted_ad',
            new_name='deleted_at',
        ),
    ]
