# Generated by Django 2.0 on 2018-11-28 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0004_auto_20171201_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server_User',
            new_name='ServerUser',
        ),
    ]
